name: dev-catenary
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - matplotlib
  - jupyter
  - ipython
  - pytorch
  - gymnasium
  - stable-baselines3
  - casadi
  - pygame
  - meshcat-python
  - tqdm
  - rosbags


